openapi: 3.0.1
info:
  title: Speco Tasker CLI API
  description: Speco Tasker 命令行接口合约 - AI功能移除后的纯手动任务管理
  version: 1.0.0
  contact:
    name: Speco Team

servers:
  - url: task-master
    description: CLI command interface

paths:
  /list:
    get:
      summary: 获取任务列表
      description: 列出所有任务或按状态过滤任务
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, in-progress, done, review, deferred, cancelled]
          description: 任务状态过滤
        - name: with-subtasks
          in: query
          schema:
            type: boolean
            default: false
          description: 是否包含子任务
        - name: tag
          in: query
          schema:
            type: string
          description: 标签上下文
      responses:
        '200':
          description: 任务列表
          content:
            text/plain:
              schema:
                type: string
                description: 格式化的任务列表文本

  /show/{id}:
    get:
      summary: 获取单个任务详情
      description: 显示指定任务或子任务的详细信息
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: '^\\d+(\\.\\d+)?$'
          description: 任务ID，支持子任务格式如 1.2
        - name: tag
          in: query
          schema:
            type: string
          description: 标签上下文
      responses:
        '200':
          description: 任务详情
          content:
            text/plain:
              schema:
                type: string
                description: 格式化的任务详情文本
        '404':
          description: 任务不存在

  /set-status:
    post:
      summary: 设置任务状态
      description: 更新任务或子任务的状态
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - status
              properties:
                id:
                  type: string
                  pattern: '^\\d+(\\.\\d+)?$'
                  description: 任务ID
                status:
                  type: string
                  enum: [pending, in-progress, done, review, deferred, cancelled]
                  description: 新状态
                tag:
                  type: string
                  description: 标签上下文
      responses:
        '200':
          description: 状态更新成功
        '400':
          description: 无效请求参数
        '404':
          description: 任务不存在

  /move:
    post:
      summary: 移动任务位置
      description: 将任务或子任务移动到新的位置
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - from
                - to
              properties:
                from:
                  type: string
                  pattern: '^\\d+(\\.\\d+)?$'
                  description: 源任务ID
                to:
                  type: string
                  pattern: '^\\d+(\\.\\d+)?$'
                  description: 目标位置ID
                tag:
                  type: string
                  description: 标签上下文
      responses:
        '200':
          description: 移动成功
        '400':
          description: 无效的移动操作
        '404':
          description: 源任务不存在

  /remove-task:
    delete:
      summary: 删除任务
      description: 永久删除指定的任务
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            pattern: '^\\d+$'
          description: 任务ID
        - name: yes
          in: query
          schema:
            type: boolean
            default: false
          description: 跳过确认提示
        - name: tag
          in: query
          schema:
            type: string
          description: 标签上下文
      responses:
        '200':
          description: 删除成功
        '404':
          description: 任务不存在

  /add-subtask:
    post:
      summary: 添加子任务
      description: 为指定任务添加新的子任务
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - title
              properties:
                id:
                  type: string
                  pattern: '^\\d+$'
                  description: 父任务ID
                title:
                  type: string
                  maxLength: 100
                  description: 子任务标题
                description:
                  type: string
                  maxLength: 300
                  description: 子任务描述
                status:
                  type: string
                  enum: [pending, in-progress, done, review, deferred, cancelled]
                  default: pending
                  description: 子任务状态
                tag:
                  type: string
                  description: 标签上下文
      responses:
        '200':
          description: 子任务添加成功
        '400':
          description: 无效请求参数
        '404':
          description: 父任务不存在

  /add-dependency:
    post:
      summary: 添加任务依赖
      description: 为任务添加依赖关系
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - dependsOn
              properties:
                id:
                  type: string
                  pattern: '^\\d+(\\.\\d+)?$'
                  description: 任务ID
                dependsOn:
                  type: string
                  pattern: '^\\d+(\\.\\d+)?$'
                  description: 依赖的任务ID
                tag:
                  type: string
                  description: 标签上下文
      responses:
        '200':
          description: 依赖关系添加成功
        '400':
          description: 会创建循环依赖
        '404':
          description: 任务不存在

  /remove-dependency:
    delete:
      summary: 移除任务依赖
      description: 删除任务之间的依赖关系
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            pattern: '^\\d+(\\.\\d+)?$'
            description: 任务ID
        - name: dependsOn
          in: query
          required: true
          schema:
            type: string
            pattern: '^\\d+(\\.\\d+)?$'
            description: 依赖的任务ID
        - name: tag
          in: query
          schema:
            type: string
            description: 标签上下文
      responses:
        '200':
          description: 依赖关系移除成功
        '404':
          description: 依赖关系不存在

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - status
      properties:
        id:
          type: integer
          minimum: 1
          description: 任务唯一标识符
        title:
          type: string
          maxLength: 100
          description: 任务标题
        description:
          type: string
          maxLength: 500
          description: 任务描述
        status:
          type: string
          enum: [pending, in-progress, done, review, deferred, cancelled]
          description: 任务状态
        dependencies:
          type: array
          items:
            type: integer
            minimum: 1
          description: 依赖任务ID数组
        priority:
          type: string
          enum: [high, medium, low]
          default: medium
          description: 任务优先级
        details:
          type: string
          description: 详细说明
        testStrategy:
          type: string
          description: 测试策略
        subtasks:
          type: array
          items:
            $ref: '#/components/schemas/Subtask'
          description: 子任务数组

    Subtask:
      type: object
      required:
        - id
        - title
        - status
      properties:
        id:
          type: integer
          minimum: 1
          description: 子任务标识符
        title:
          type: string
          maxLength: 100
          description: 子任务标题
        description:
          type: string
          maxLength: 300
          description: 子任务描述
        status:
          type: string
          enum: [pending, in-progress, done, review, deferred, cancelled]
          description: 子任务状态
        dependencies:
          type: array
          items:
            type: integer
            minimum: 1
          description: 依赖子任务ID数组
        details:
          type: string
          description: 子任务详细说明

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: 错误信息
        code:
          type: string
          description: 错误代码
        details:
          type: object
          description: 错误详情
